#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# One-shot DKMS installer for the msa1-ec module.
# Prerequisite: packaging/setup-mok.sh has been run AND its key is enrolled.

set -euo pipefail

PKG=msa1-ec
VER=0.1.0
SRC_ROOT="$(cd "$(dirname "$(readlink -f "$0")")"/.. && pwd)"
DEST=/usr/src/${PKG}-${VER}

MOK_DIR=/var/lib/shim-signed/mok
MOK_PRIV="$MOK_DIR/msa1.priv"
MOK_DER="$MOK_DIR/msa1.der"
FRAMEWORK_CONF=/etc/dkms/framework.conf.d/msa1.conf
KEY_CN="msa1-ec module signing key"

if [[ $EUID -ne 0 ]]; then
    echo "Run as root: sudo $0" >&2
    exit 1
fi

# -------------------------------------------------------------------------
# Pre-flight checks
# -------------------------------------------------------------------------

if ! command -v dkms >/dev/null; then
    echo "ERROR: dkms not installed.  Try: sudo apt install dkms" >&2
    exit 1
fi

if [[ ! -r $MOK_PRIV || ! -r $MOK_DER ]]; then
    echo "ERROR: MOK key not found at $MOK_PRIV / $MOK_DER" >&2
    echo "       Run: sudo bash packaging/setup-mok.sh" >&2
    exit 1
fi

if ! mokutil --sb-state 2>/dev/null | grep -q "SecureBoot enabled"; then
    echo "NOTE: Secure Boot is NOT enabled -- signing is optional but harmless."
fi

if ! mokutil --list-enrolled 2>/dev/null | grep -q "$KEY_CN"; then
    echo "WARNING: '$KEY_CN' is not enrolled in MOK yet."
    echo "         The module will build but the kernel may REJECT loading it"
    echo "         until you reboot and complete MOK Manager enrollment."
    read -rp "Continue anyway? [y/N] " yn
    case "${yn,,}" in
        y|yes) ;;
        *) exit 1 ;;
    esac
fi

# -------------------------------------------------------------------------
# DKMS framework config -- tell DKMS which key to sign with
# -------------------------------------------------------------------------

install -d /etc/dkms/framework.conf.d
cat > "$FRAMEWORK_CONF" <<EOF
# Auto-generated by packaging/install.sh
# Per-module signing config picked up by DKMS for msa1-ec builds.
mok_signing_key="$MOK_PRIV"
mok_certificate="$MOK_DER"
sign_tool="/usr/lib/dkms/sign_helper.sh"
EOF
echo "Wrote $FRAMEWORK_CONF"

# -------------------------------------------------------------------------
# Stage source tree
# -------------------------------------------------------------------------

echo "Installing source to $DEST ..."
rm -rf "$DEST"
install -d "$DEST"
cp -r "$SRC_ROOT/src" "$SRC_ROOT/dkms.conf" "$DEST/"

# -------------------------------------------------------------------------
# Add / build / install with DKMS
# -------------------------------------------------------------------------

# Always do a clean rebuild so source changes take effect.
if dkms status -m "$PKG" -v "$VER" 2>/dev/null | grep -q "$PKG"; then
    echo "Removing existing DKMS build for $PKG/$VER ..."
    dkms remove -m "$PKG" -v "$VER" --all >/dev/null 2>&1 || true
fi
dkms add -m "$PKG" -v "$VER"

echo
echo "Building..."
dkms build -m "$PKG" -v "$VER"

echo
echo "Installing..."
dkms install --force -m "$PKG" -v "$VER"

# -------------------------------------------------------------------------
# Smoke test
# -------------------------------------------------------------------------

echo
echo "Loading module..."
modprobe -r msa1_ec 2>/dev/null || true
if ! modprobe msa1_ec; then
    echo "ERROR: modprobe failed.  Recent dmesg:" >&2
    dmesg | tail -20 >&2
    exit 1
fi

sleep 1
echo
echo "=== dmesg ==="
dmesg | tail -10 | grep -i msa1_ec || echo "(no msa1_ec dmesg yet -- check 'dmesg' manually)"

echo
echo "=== hwmon device ==="
found=""
for h in /sys/class/hwmon/hwmon*; do
    if [[ -e $h/name ]] && [[ "$(cat "$h/name")" == "msa1_ec" ]]; then
        echo "  $h -> msa1_ec"
        echo "  contents:"
        ls "$h" | grep -E '^(temp|fan)[0-9]+_(input|label)$' | while read -r f; do
            printf "    %-15s = %s\n" "$f" "$(cat "$h/$f")"
        done
        found=1
    fi
done
[[ -z $found ]] && echo "  no msa1_ec hwmon device -- check dmesg"

echo
echo "Done.  Try:"
echo "  sensors | grep -A6 msa1_ec"
echo "  sudo cat /sys/kernel/debug/msa1_ec/dump_d5"
